### PR TITLE
Update bokeh =>2.0.0

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
There are some backwards incompatible changes between bokeh version 1.* and 2.* This PR attempts to address them.

Related: https://github.com/microscopium/microscopium/issues/173

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Right now you can load the microscopium webpage (I've been using the demo data, as described in the README).

Still needs fixing: when you click/select points in the left hand side graph, the image data isn't being copied properly and displayed on the right hand side. I think this is another backwards incompatible thing, will need to look into it later.

```
ready!
WARNING:bokeh.server.util:Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly
Web app now available at http://localhost:5000
BokehDeprecationWarning: 'WidgetBox' is deprecated and will be removed in Bokeh 3.0, use 'bokeh.models.Column' instead
BokehDeprecationWarning: 'WidgetBox' is deprecated and will be removed in Bokeh 3.0, use 'bokeh.models.Column' instead
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.97ms
new index:  [0]
ERROR:bokeh.server.protocol_handler:error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1049'}, 'attr': 'indices', 'new': [0]}], 'references': []} 
 error: ValueError('\nColumnDataSource.data properties may only be set from plain Python dicts,\nnot other ColumnDataSource.data values.\n\nIf you need to copy set from one CDS to another, make a shallow copy by\ncalling dict: s1.data = dict(s2.data)\n')
Traceback (most recent call last):
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/document/document.py", line 1169, in _with_self_as_curdoc
    return f()
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/document/document.py", line 410, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/has_props.py", line 345, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 610, in set_from_json
    return super().set_from_json(obj,
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 321, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 763, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 832, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 909, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/model.py", line 664, in trigger
    super().trigger(attr, old, new, hint=hint, setter=setter)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 157, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/document/document.py", line 1061, in _notify_change
    self._trigger_on_change(event)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/document/document.py", line 1151, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/document/document.py", line 1169, in _with_self_as_curdoc
    return f()
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 155, in invoke
    callback(attr, old, new)
  File "/home/genevieve/GitHub/microscopium/microscopium/serve.py", line 377, in load_selected
    update_table(new, dataframe, table)
  File "/home/genevieve/GitHub/microscopium/microscopium/serve.py", line 301, in update_table
    table.source.data = ColumnDataSource(filtered_df).data
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/has_props.py", line 278, in __setattr__
    super().__setattr__(name, value)
  File "/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 969, in __set__
    raise ValueError(_CDS_SET_FROM_CDS_ERROR)
ValueError: 
ColumnDataSource.data properties may only be set from plain Python dicts,
not other ColumnDataSource.data values.

If you need to copy set from one CDS to another, make a shallow copy by
calling dict: s1.data = dict(s2.data)

/home/genevieve/anaconda3/envs/mic/lib/python3.9/site-packages/bokeh/server/protocol_handler.py:94: RuntimeWarning: coroutine 'WSHandler.send_message' was never awaited
  work = connection.error(message, repr(e))
```

**Comment by GenevieveBuckley** [comment]
Ok I think this works now, @jni you can take a look at it.

**Comment by jni** [comment]
It works! 🎉 😊  I cleaned up the requirements a bit, looks like some unused stuff snuck in there in the past.

**Comment by Gpotier** [comment]
Thanks @GenevieveBuckley and @jni, great work  :+1:

**Pull request merged**
