### PR TITLE
Update Mongo query in metrics.py to be PyMongo3 compatible

### PR DESCRIPTION
**Pull request by starcalibre**
So this was pretty easy, see the PyMongo [docs](http://api.mongodb.org/python/current/api/pymongo/collection.html#pymongo.collection.Collection.aggregate). PyMongo 3.x returns a cursor from an aggregation query now. The cursor isn't accessed with the ``result`` key anymore.

### CODE REVIEW

**Comment by jni** [comment]
This is what you get for writing such a cocky PR message. =P Looks like Py2.7 is failing, reliably this time. Not sure what the deal is — something ports-related? From PyMongo:

```
ServerSelectionTimeoutError: No servers found yet
```

**Comment by starcalibre** [comment]
I couldn't help but open my big mouth :P It looks like this is a known bug -- https://jira.mongodb.org/browse/PYTHON-961

It's been fixed but not rolled out yet. There's apparently a work workaround, which is to call ``connect=False`` in the ``MongoClient`` constructor. This doesn't work for me on my local 2.7 environment. Hmm..

**Comment by jni** [comment]
LOL

Since we know the root cause and that there's a fix on the way, I'm happy to merge this for now — perhaps comment-out the Py27 testing for now? We can reactivate once 3.0.4 is out.

**Comment by starcalibre** [comment]
I'd rather just shelve this until there's a new release of PyMongo. There's no benefit to updating for the time being.

**Comment by jni** [comment]
Fair enough. =)

**Comment by sibeliusseraphini** [comment]
PyMongo 3.2 fixed this issue

**Comment by jni** [comment]
@sibeliusseraphini Thanks for letting us know!

@starcalibre it looks like some of the tests are erroring now, do you want to troubleshoot and get this merged finally?
https://travis-ci.org/microscopium/microscopium/jobs/83814604

**Comment by starcalibre** [comment]
@jni PyMongo works fine now, but it looks like the errors are due to a conflict in ``OnlineStandardScaler``. ``scikit-learn`` changed their ``StandardScaler`` in version 0.17.0. I'm working on it!

**Comment by starcalibre** [comment]
@jni Passing now! ``scikit-learn`` added online standard scaling to their ``StandardScaler``, so refactoring ``run_features`` slightly to use it sorted out the conflict. I'll leave it up to you whether or not we keep your ``OnlineStandardScaler`` in the code?

Side-note: MPL 1.5.1 throws a warning during the Travis build (that's why there's a bit of commit ping-pong between fixing and fixing the version, was trying to see if fixing MPL to 1.5.0 stopped the warning). This warning was added in MPL 1.5.1 (see https://github.com/matplotlib/matplotlib/issues/5836). Seeing as the build still passes I'm not worried about it too much..

**Comment by jni** [comment]
@starcalibre awesome! Yeah I've encountered that warning. What a PITA. It should be fixed by adding a few directories to travis cache. I'll do that in a separate PR. Thanks for getting this through! Woot! =)

**Pull request merged**
