### PR TITLE
Fix the sq_to_dist function

### LINKED ISSUE #26: A bug in the sq_to_dist function
Hi, the sq_to_dist function in metrics.py is returning a wrong index. The test call in the doc_string also returns the wrong value.

### PR DESCRIPTION
**Pull request by sahas111**
The function was returning a wrong index and I have changed
the index calculation.

Fixes #26

### CODE REVIEW

**Comment by sahas111** [comment]
I find that my last modifications on the sq_to_dist function is  also not returning correct values in all cases. I was arbitrarily checking the function with some arbitrary values. Co-incidently for those values we only needed to add 1 with the original calculation. But for the other i, j & n values it is not working. The original function itself is also not producing consistent values for each index which means some are correct and some are not.

Actually the total index calculation needs to be changed. 

Here is the modified function with the right index calculation and some tests:

```python
In [46]: def sq_to_dist(i, j, n):
                  index =i*n + j - i*(i+1)/2 - i - 1
                  return int(index)
   
In [47]: sq_to_dist(0,1,4)
Out[47]: 0

In [48]: sq_to_dist(1,2,4)
Out[48]: 3
```

**Comment by jni** [comment]
Very nice, @sahas111! Could you add this to the PR?

- could you add a new doctest that distinguishes between the three methods? ie one or two examples that only your method gets right. Follow the same format as the existing doctest, (with the `>>>`), just in a new line.
- I actually realised that using `sq_to_dist` to determine the length is actually super stupid LOL. So don't use that. Firstly: near the top, write `nsamples = X.shape[0]`. That way, you only need to check it once and it's more readable. Then, `n = int(nsamples * (nsamples - 1) / 2)`.
- And, again, `n` is not very readable: change that name to `npairs`. =)
- Finally, add a "References" section to the docstring (see [NumPy docstring conventions](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)) pointing people to the actual definition of the indexing [here](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.squareform.html). This is actually what I used to verify your formula: theirs indeed reduces to yours. =)

**Comment by jni** [comment]
@sahas111 I've added some comments that should be quick to fix...!

**Comment by jni** [comment]
@starcalibre As you can see in the discussion above, your calculation of the `sq_to_dist` index was incorrect before. Somehow it slipped past both of us! @sahas111 did a good job catching it, but now some of the tests are not passing — can you have a look at them?

**Comment by jni** [comment]
BOOM. =) Thank you so much, @sahas111!

**Pull request merged**
